name: Run Tests

on:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Requirements
        run: |
          python -c "import sys; print(sys.version)"
          pip install --no-cache-dir --upgrade --requirement requirements.txt
          pip install --no-cache-dir --upgrade --requirement requirements-dev.txt
          python setup.py install

      - name: Run tests
        env:
          FANTRAX_USERNAME: ${{ secrets.FANTRAX_USERNAME }}
          FANTRAX_PASSWORD: ${{ secrets.FANTRAX_PASSWORD }}
          LEAGUE_ID: ${{ secrets.LEAGUE_ID }}
          LOCAL: False
        run: coverage run -m pytest -s --cov fantraxapi --cov-report xml

      - name: Codecov coverage reports
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
